on: 
  [push, pull_request]

name: Continuous Integration

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
      - name: Setup Autoprefixer
        run: npm i -D autoprefixer && npm install postcss
      - name: Build site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
          jekyll_src: site
          custom_opts: --config _config.yml --trace
        env:
          JEKYLL_ENV: ci
          
